server {
    listen 80;
    index index.php index.html;

    # Pointe vers le dossier public de Laravel
    root /var/www/public;

    # Pour React Router ou les URLs Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Traiter les fichiers PHP avec PHP-FPM
    location ~ \.php$ {
        fastcgi_pass app:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Cacher les fichiers .htaccess
    location ~ /\.ht {
        deny all;
    }
}
